name: roboadvisor-app
region: fra1

services:
  - name: api
    github:
      repo: ZwenAusZwota/roboadvisor-frontend
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET
        scope: RUN_TIME

static_sites:
  - name: web
    github:
      repo: ZwenAusZwota/roboadvisor-frontend
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
