name: roboadvisor-app
region: fra1

static_sites:
  - name: web
    github:
      repo: ZwenAusZwota/roboadvisor-frontend
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: dist
    environment_slug: node-js
    routes:
      - path: /
