name: roboadvisor-app
region: fra1

static_sites:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/roboadvisor-app
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /

